language: python
dist: xenial
python:
  - "3.7"
  - "3.6"

services:
  - docker

cache:
  - pip

install:
  - make init

before_script:
  - make start

script:
  - make test

after_script:
  - make stop

after_success:
  - make codecov

notifications:
  email: false
